### ISSUE TITLE
No headline1,2,3,4,5

### ISSUE THREAD

**Issue by idootop** [michaelroudnitski/Tabs#16]
![Snipaste_2020-01-28_18-05-52](https://user-images.githubusercontent.com/35302658/73254239-fa953a00-41f8-11ea-8c91-da9f72e28a02.png)

Flutter SDK 1.12.13+hotfix.5

**Comment by michaelroudnitski** [comment]
Flutter SDK 1.14.6-pre.49

running `flutter upgrade` should resolve, I upgraded last night and they updated the text themes.

**Comment by idootop** [comment]
Cool. Thanks a lot.
