### ISSUE TITLE
The named parameter 'builder' isn't defined.

### ISSUE THREAD

**Issue by idootop** [michaelroudnitski/Tabs#17]
![Snipaste_2020-01-28_18-11-35](https://user-images.githubusercontent.com/35302658/73254620-b8202d00-41f9-11ea-8236-21ff48c6333b.png)

What's your Flutter SDK version?
Can you update it?

**Comment by idootop** [comment]
I think it's provider's version's problem.
![Snipaste_2020-01-28_18-19-14](https://user-images.githubusercontent.com/35302658/73255194-b6a33480-41fa-11ea-8f9c-4059b162eaa1.png)
Which version of provider did you use?

**Comment by michaelroudnitski** [comment]
Current version of Provider is 3.1.0+1

My mistake, I should definitely be adding version numbers when adding packages.

Provider recently jumped from v3 to v4 so I'm doing a quick migration to v4. The change that breaks v3 was the removal of `builder` for `create`.
